### ISSUE TITLE
MQTT Trigger : Need received message as output parameter

### ISSUE THREAD

**Issue by ecarlier-tibco** [TIBCOSoftware/flogo-contrib#11]
In order to be able to use this trigger, we need to be able to get and parse the received message.
Likely then require some king of json parser activity as usual format of message content is JSON

Thanks

**Comment by kwaehner** [comment]
As a first (simple) step, it should at least be possible to forward the content of the message (without any parsing) to the next activity. This should be very easy to be implemented quickly with a few lines of code.

**Comment by lixingwang** [comment]
Now only support text message and add message output field for mqtt trigger.
