### ISSUE TITLE
MQTT trigger deadlocks if replyTo is empty

### ISSUE THREAD

**Issue by torresashjian** [TIBCOSoftware/flogo-contrib#118]
We need to add the right checks and a timeout for the publish message after calling the flow.

**Comment by torresashjian** [comment]
Fixed

**Comment by mgdevstack** [comment]
I have checked MQTT trigger implementation code base but there is no statement which actually updates **StartRequest.RepyTo** struct field. This is the reason we face **Warning: Invalid empty topic to publish to** and desired result is not retrieved (flow deadlock).

@torresashjian, plz have look at PR #144.
