### ISSUE TITLE
Issue with custom activity in linux

### ISSUE THREAD

**Issue by kawatoto** [TIBCOSoftware/flogo-contrib#157]
Hi Team,

I’m trying to create a custom flogo activity, I tried to to it with Mac and it works fine, but when tried to use linux (CentOS) to install the test package as is mentioned in the doc 

![image](https://user-images.githubusercontent.com/1425127/33023603-50dea35c-cdce-11e7-9942-ad7c5bae11de.png)

I’m getting the below message error message:

> [adavilag@adavilag-centOS test]$ go get github.com/TIBCOSoftware/flogo-contrib/action/flow/test
>  github.com/TIBCOSoftware/flogo-contrib/action/flow/test
> ./context.go:226:10: cannot use c.ACtx (type *TestActionCtx) as type action.Context in return argument:
> 	*TestActionCtx does not implement action.Context (missing GetResolver method)

Do you have any idea what could be the issue?

Thanks in advance,
Antonio

**Comment by fm-tibco** [comment]
Hi Antonio, I checked in a fix for your issue, please give it a try and let us know if your problem is resolved

**Comment by kawatoto** [comment]
Hi Frank,
Thanks! it solved the previous error but now I'm getting this one:

```
./activity_test.go:54:10: cannot use tc (type *test.TestActivityContext) as type activity.Context in argument to act.Eval:
	*test.TestActivityContext does not implement activity.Context (missing ActionContext method)
FAIL	_/home/adavilag/go/bin/FTLogo [build failed]
```

**Comment by fm-tibco** [comment]
Can you look at the "github.com/TIBCOSoftware/flogo-contrib/action/flow/test/context.go" file and see if you have the following code at line 230

```
func (c *TestActivityContext) ActionContext() action.Context {
	return c.ACtx
}
```

**Comment by kawatoto** [comment]
Yes, but it is in line 225

![image](https://user-images.githubusercontent.com/1425127/33035923-6daceb32-cdf2-11e7-891c-a077baa9751e.png)

**Comment by fm-tibco** [comment]
Looks like your flogo code might be outdated...  take a look at [github.com/TIBCOSoftware/flogo-contrib/action/flow/test/context.go](https://github.com/TIBCOSoftware/flogo-contrib/blob/master/action/flow/test/context.go )

Last line should be 232

**Comment by kawatoto** [comment]
It seems to be working now, thank you!
