### ISSUE TITLE
Web socket activity is not closed?

### ISSUE THREAD

**Issue by philippegabert** [TIBCOSoftware/flogo-contrib#165]
Hi there,

We are using the websocket activity to send some data but after a while we received read timed out error from our websocket receiver. 
That makes me think that the connection is not closed and dies after a while...

When reading at the code of the activity I don't see any closing of the connection...

So... is the connection closed? Or should the code be corrected?

Thanks

Philippe

**Comment by philippegabert** [comment]
Well, I did fork the activity code to try by myself... Closing the socket solved all my troubles.

I  think this should be corrected.

Philippe

**Comment by mellistibco** [comment]
Thanks @philippegabert. Feel free to create a PR for the fix :)

**Comment by philippegabert** [comment]
Hi @mellistibco, 

already have a PR being reviewed... Don't want to merge the edit in my current PR and don't want to create a branch on my PR just for this purpose (Completely unrelated to the first PR)

Cheers

**Comment by mellistibco** [comment]
resolved in pr #172
