### ISSUE TITLE
Flow iterators

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo-contrib#169]
As a flow developer I want to iterate over arrays inline, within the flow. For example, invoke a REST activity, the result is an array, iterate over the array and execute a single activity. We should expose an index object and perhaps a ref to the current object.

If complex logic needs to be executed in an iteration, a subflow invoke can be leveraged.

**Comment by ayh20** [comment]
Please, please .... PLEASE ;-)

**+1**

**Comment by mellistibco** [comment]
Implemented in #196
