### ISSUE TITLE
Does Aggregate action have wrong "ref" definition?

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/flogo-contrib#185]
Currently in activity.json:
"ref": "github.com/TIBCOSoftware/flogo-contrib/activity/aggregator",
"homepage": "https://github.com/TIBCOSoftware/flogo-contrib/tree/master/activity/aggregator",

Should these be changed to followings?
"ref": "github.com/TIBCOSoftware/flogo-contrib/activity/aggregate",
"homepage": "https://github.com/TIBCOSoftware/flogo-contrib/tree/master/activity/aggregate",

**Comment by mellistibco** [comment]
thanks @lwlwlwlw. resolved.
