### ISSUE TITLE
Error in action/flow/test/model.go

### ISSUE THREAD

**Issue by mcrodrig** [TIBCOSoftware/flogo-contrib#198]
In function Eval the interface expects as return a model.EvalResult, but it returns boolean in the first if. Marked with **

```
func (b *SimpleTaskBehavior) Eval(context **model.TaskContext**, evalCode int) (evalResult model.EvalResult, doneCode int, err error) {

	task := context.Task()
	logger.Debugf("Task Eval: %v\n", task)

	if len(task.ChildTasks()) > 0 {
		logger.Debugf("Has Children\n")

		context.SetState(STATE_WAITING)

		//for now enter all children (bpel style) - costly
		context.EnterChildren(nil)

		return **false**, 0, nil
	}

	if context.HasActivity() {

		//log.Debug("Evaluating Activity: ", activity.GetType())
		done, _ := context.EvalActivity()
		if done {
			evalResult = model.EVAL_DONE
		} else {
			evalResult = model.EVAL_WAIT
		}

		return evalResult, 0, nil
	}

```

**Comment by pradyuz3rocool** [comment]
The same error is also coming when i try to do the following

go get github.com/TIBCOSoftware/flogo-contrib/action/flow/test

it is giving an error message as follows

# github.com/TIBCOSoftware/flogo-contrib/action/flow/test
../../go-workspace/src/github.com/TIBCOSoftware/flogo-contrib/action/flow/test/model.go:104:3: cannot use false (type bool) as type model.EvalResult in return argument
