### ISSUE TITLE
data type values are not in sync with flogo-lib core data types

### ISSUE THREAD

**Issue by nareshkumarthota** [TIBCOSoftware/flogo-contrib#221]
In all the json files present in triggers and activity, type attribute mentioned as string, int and long etc. But in flogo-lib/core/data/types.go file they are mentioned as integer number etc. They both are not in sync. While creating kafka trigger app with latest code its breaking.
Error is mentioned as
"panic: Unable to parse activity metadata: unknown data type: int" 

data type mentioned in trigger.json is different from allowed types in types.go file.
NOTE: not only in trigger.json there might be other json files in activity etc.

**Comment by fm-tibco** [comment]
The issue arose after we added validation for the types.  The types will now accept int as an alias to integer.
