### ISSUE TITLE
Ability to route multiple trigger points to the same action handler

### ISSUE THREAD

**Issue by balamg** [TIBCOSoftware/flogo-contrib#269]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[X] enhancement request
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**

**Expected behavior:**
Ability to specify in the flogo.json file, multiple triggers pointing to the same action. This is required where you want to correlate event streams

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**
For use in a new action for correlation purposes

**Please tell us about your environment (Operating system, docker version, browser & verison if webui, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fm-tibco** [comment]
Created a pull request for this issue:

https://github.com/TIBCOSoftware/flogo-lib/pull/208

**Comment by fm-tibco** [comment]
This issue has been fixed, please refer to the updated app model
https://github.com/TIBCOSoftware/flogo/wiki/App-Model
