### ISSUE TITLE
Trigger/Activity name should be supported in the mappings

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo-contrib#63]
For expression mappings, instead T(trigger)/A(activity) we should be able to use trigger/activity name.
e.g. $A3.response.code should be $Rest-Invoke.response.code or $T.queryParams.content-length should be $Rest-Trigger.queryParams.content-length
This will be helpful in using same expression for both design-time and runtime.

**Comment by fm-tibco** [comment]
Fixed, added ability to specify a default Task Output Mapper.  Naming scheme no longer imposed by the flow action for activities.
