### ISSUE TITLE
CoAP trigger: ACK token

### ISSUE THREAD

**Issue by Adirio** [TIBCOSoftware/flogo-contrib#93]
When a confirmable (CON) message gets acknowleded, the token has been commented out:
```
269	res := &coap.Message{
270		Type:      coap.Acknowledgement,
271		Code:      0,
272		MessageID: msg.MessageID,
273		//Token:     msg.Token,
274		//Payload:   payload,
275	}
```
While the payload has been properly commented out as it doesn't send any payload, the token is needed. Most client implementations do not check it after validating the ACKs message id, but some do as the spec asks for and they will find out that the tokens do not match.

**Comment by Adirio** [comment]
I would apreciate some feedback. I can submit a pull request myself but will not develop anything until one of the developers approves it.

**Comment by fm-tibco** [comment]
Yes, that should be uncommented.  You can submit a pull request or we can fix it.
