### ISSUE TITLE
CoAP trigger: HandlerCfg.autoIdReply and CoapResource.attrs

### ISSUE THREAD

**Issue by Adirio** [TIBCOSoftware/flogo-contrib#94]
They seem to be old unused features. What was they for?

Will they get re-implemented or should they be cleaned up?

**Comment by Adirio** [comment]
I would apreciate some feedback. I can submit a pull request myself but will not develop anything until one of the developers approves it.

**Comment by fm-tibco** [comment]
These should be cleaned up, go ahead and submit a pull request.
