### ISSUE TITLE
Error with new trigger: panic: index out of range

### ISSUE THREAD

**Issue by Adirio** [TIBCOSoftware/flogo-contrib#98]
I'm trying to develop a new trigger and I'm getting the following error on runtime:
```
panic: runtime error: index out of range

goroutine X [running]:
github.com/TIBCOSoftware/flogo-contrib/action/flow.(*FlowAction).Run(...)
C:/Users/.../Go/src/myApp/vendor/src/github.com/TIBCOSoftware/flogo-contrib/action/flow/action.go:214 +0x3fc
```
Those lines are:
```
208	triggerAttrs, ok := trigger.FromContext(context)
209
210	if ok {
211		if len(triggerAttrs) > 0 {
212			logger.Debug("Run Attributes:")
213			for _, attr := range triggerAttrs {
214				logger.Debugf(" Attr:%s, Type:%s, Value:%v", attr.Name, attr.Type.String(), attr.Value)
215			}
216		}
217	}
```
So I deducted it was something to do with the output I was sending. My `trigger.go`, with some comments with the go type of the variables, looks like this:
```
data := map[string]interface{}{
	"extended": ext, // bool
	"rtr": rtr, // bool
	"error": err, // bool
	"id": id, // uint32
	"length": length, // uint8
	"payload": payload, // [8]uint8 or [64]uint8
}
startAttrs, _ := t.metadata.OutputsToAttrs(data, false)
ctx := trigger.NewContext(context.Background(), startAttrs)
t.runner.Run(ctx, action.Get(actionId), actionId, nil)
```
The corresponding `trigger.json` looks like this:
```
"outputs": [
    {
      "name": "extended",
      "type": "boolean"
    },
    {
      "name": "rtr",
      "type": "boolean"
    },
    {
      "name": "error",
      "type": "boolean"
    },
    {
      "name": "id",
      "type": "integer"
    },
    {
      "name": "length",
      "type": "integer"
    },
    {
      "name": "payload",
      "type": "bytearray"
    }
  ]
```
When I copied into my `trigger.go` the lines that were panic-ing, modifying the variable names and scopes as needed, I managed to print in the console:
```
Run Attributes:
Attr:extended, Type:boolean, Value:false
Attr:rtr, Type:boolean, Value:false
Attr:error, Type:boolean, Value:false
Attr:id, Type:integer, Value:50
Attr:length, Type:integer, Value:0
```
But the `payload` field does not get printed. I'm not sure what am I doing wrong. If you need any further information, please, ask for it.

**Comment by Adirio** [comment]
**Update:** removing the `payload` output both in the `trigger.go` and `trigger.json` so it seems it has some problem with the `[X]uint8` array. How should I pass the payload then? Or how should I specify it is an array in the `trigger.json` file?

**Comment by Adirio** [comment]
**Update:** Setting it to `"array"` in the `.json` file seems to have solved the problem but wasn't able to find any documentation nor the part of the code where this assertion is being made. Pointers to any of those two parts would be welcome.

**Comment by fm-tibco** [comment]
I'll look into the "index out of range" and output not showing.  At a minimum try to give a more constructive error to help diagnose the problem.

Also, we are working on cleaning put and adding additional documentation.  Please create a documentation issue  which we can address separately.  Thank you.

**Comment by Adirio** [comment]
I tracked the error as much as I could but wasn't able to find more. Using `"type": "bytearray"` in the `trigger.json` file was yielding the error while `"type": "array"` isn't. Is there any kind of parsing being done depending on this config parameter? If the answer is yes, ¿what types am I able to use? I thought this was just some kind of meta config information that the trigger could use to parse it but that wasn't being used by the engine itself.

**Comment by fm-tibco** [comment]
Yes, the issue is that we currently do not have an explicit bytearray type.  The types that you can use can be found at [flogo types](https://github.com/TIBCOSoftware/flogo-lib/blob/master/core/data/types.go)
We'll have to create a separate issue for type validation so you don't get this obscure errors.
